apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-my
  labels:
    app.kubernetes.io/name: debug-my
  name: debug-my
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: debug-my
  template:
    metadata:
      labels:
        app.kubernetes.io/name: debug-my
    spec:
      containers:
      - image: docker.blackbird.si/debug-my:latest
        name: debug-my
      imagePullSecrets:
      - name: docker-blackbird-si
      dnsConfig:
            options:
              - name: ndots
                value: "2"

---

apiVersion: v1
kind: Service
metadata:
  name: debug-my
  labels:
    app.kubernetes.io/name: debug-my
spec:
  selector:
    app.kubernetes.io/name: debug-my
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
